### ISSUE TITLE
 Use Case 5 - Ask to Follow a Participant

### ISSUE THREAD

**Issue by bbest31** [CMPUT301W17T22/MoodSwing#22]
Tabbed Page to view Followers, Following, and Pending.
Be able to send a Request to follow a participant and have that participant see they have a request.

**Comment by bbest31** [comment]
Model classes that handle this are done, need tests and to hook up to the UI

**Comment by nyitrch** [comment]
We are going to need to redo how we do following/follower stuff. Right now as we have it, we store lists of participants. But those participants then store lists of participants, including the first participant that has a list with this participant in it. It leads to a recursive and infinitely large list. I discovered this problem when trying to put the participants to ElasticSearch. Gson cant serialize them because they are so large they overflow the stack they are on. I tried changing it to a list of usernames, but found out the way I was doing it broke so much it wasn't worth going forward with. I will try again to work on this later.
