### ISSUE TITLE
Enter in any classes we're missing for unit tests

### ISSUE THREAD

**Issue by peterweckend** [CMPUT301W17T22/MoodSwing#9]
Comment below what classes we don't have but still need so we can make those (and the unit tests that come with them).

**Comment by fdrury** [comment]
Something to do with locations...
I don't know if this will be implemented inside of MoodEvent or if it will require it's own class.
Either way it will require its own unit tests.

Probably a class to handle the map.

We're currently treating locations/mapping as a black box so we might want to create an issue to have someone start implementing it so that we have a better idea of what kinds of unit tests we will need?

**Comment by htruong4** [comment]
I think a class to handle the map is a good start. I'm not quite sure about fetching the local 5 km mood data though. Maybe it can be it's own thing when the app starts as well like how we have a load save and etc in our UML.

**Comment by peterweckend** [comment]
so Fred's working on the locations, do we need anything else? I can research anything else we might need, otherwise I'm free to help on the UML

**Comment by htruong4** [comment]
From facebook group chat, Chris mentioned that "There needs to be controllers for the following and follower lists. There isn't anything on the View end of the MVC, the controller needs to be fleshed out too, I don't think it has any methods at all".
